name: rando
description: "create and share lists"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.1.0
  # Auth
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  # Data
  provider: ^6.1.2
  json_annotation: ^4.9.0
  rxdart: ^0.27.7
  # User Files
  image_picker: ^1.1.2
  # Security
  crypto: ^3.0.3
  flutter_dotenv: ^5.0.2
  dotenv: ^4.2.0
  # Logs
  logger: ^2.4.0
  image: ^4.2.0
  image_cropper: ^7.1.0
  path_provider: ^2.1.3
  flutter_image_compress: ^2.3.0
  # flutter_launcher_icons: ^0.13.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.0.0-nullsafety
  sqflite: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # data
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

# flutter_icons:
#   android: true
#   ios: true
#   image_path: 'assets/app_icon.png'

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/
