name: app_ui
description: App UI package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  api_client:
    path: ../api_client
  auto_size_text: ^3.0.0
  cached_network_image: ^3.0.0-nullsafety
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.3.0
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  image: ^4.2.0
  image_cropper: ^7.1.0
  image_picker: ^1.1.2
  intl: ^0.18.1
  path_provider: ^2.1.3

dev_dependencies:
  very_good_analysis: ^5.1.0