name: post_repository
description: Post repository.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  api_client:
    path: ../api_client
  app_core:
    path: ../app_core
  board_repository:
    path: ../board_repository
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  user_repository:
    path: ../user_repository

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  very_good_analysis: ^5.1.0
